---@class gt.HexColor string

---@class gt.LspPalette
---@field public ref_txt gt.HexColor

---@class gt.PMenuPalette
---@field public bg gt.HexColor
---@field public sbar gt.HexColor

---@class gt.GitPalette
---@field public add gt.HexColor
---@field public change gt.HexColor
---@field public delete gt.HexColor
---@field public conflict gt.HexColor
---@field public ignore gt.HexColor
---@field public renamed gt.HexColor

---@class gt.DiffPalette
---@field public add gt.HexColor
---@field public add_fg gt.HexColor
---@field public change gt.HexColor
---@field public change_fg gt.HexColor
---@field public delete gt.HexColor
---@field public delete_fg gt.HexColor

---@class gt.SyntaxPalette
---@field public comment gt.HexColor
---@field public constant gt.HexColor
---@field public string gt.HexColor
---@field public variable gt.HexColor
---@field public keyword gt.HexColor
---@field public func gt.HexColor
---@field public func_param gt.HexColor
---@field public match_paren_bg gt.HexColor
---@field public tag gt.HexColor
---@field public html_arg gt.HexColor
---@field public param gt.HexColor
---@field public json_label gt.HexColor

---@class gt.GitSignPalette
---@field public add gt.HexColor
---@field public change gt.HexColor
---@field public delete gt.HexColor

---@class gt.ColorPalette
---NONE Color
---@field public none gt.HexColor
---Background Colors
---@field public bg gt.HexColor
---@field public bg2 gt.HexColor
---Foreground Colors
---@field public fg gt.HexColor
---@field public fg_dark gt.HexColor
---@field public fg_gutter gt.HexColor
---@field public fg_light gt.HexColor
---@field public fg_term gt.HexColor
---Background Highlights Colors
---@field public bg_highlight gt.HexColor
---@field public bg_search gt.HexColor
---@field public bg_visual gt.HexColor
---@field public bg_visual_selection gt.HexColor
---@field public border gt.HexColor
---Cursor & LineNumber Colors
---@field public cursor gt.HexColor
---@field public cursor_line_nr gt.HexColor
---@field public line_nr gt.HexColor
---LSP & Diagnostic Colors
---@field public error gt.HexColor
---@field public warning gt.HexColor
---@field public info gt.HexColor
---@field public hint gt.HexColor
---@field public lsp gt.LspPalette
---DropDown Menu Colors
---@field public pmenu gt.PMenuPalette
---Git Colors
---@field public git gt.GitPalette
---Git-Diff Colors
---@field public diff gt.DiffPalette
---Syntax Related Colors
---@field public syntax gt.SyntaxPalette
---Terminal Colors
---@field public orange gt.HexColor
---@field public black gt.HexColor
---@field public bright_black gt.HexColor
---@field public white gt.HexColor
---@field public bright_white gt.HexColor
---@field public red gt.HexColor
---@field public bright_red gt.HexColor
---@field public green gt.HexColor
---@field public bright_green gt.HexColor
---@field public yellow gt.HexColor
---@field public bright_yellow gt.HexColor
---@field public blue gt.HexColor
---@field public bright_blue gt.HexColor
---@field public magenta gt.HexColor
---@field public bright_magenta gt.HexColor
---@field public cyan gt.HexColor
---@field public bright_cyan gt.HexColor
---Configurable Dynamic Colors
---@field public sidebar_eob gt.HexColor
---@field public eob gt.HexColor
---@field public bg_nc_statusline gt.HexColor
---@field public bg_sidebar gt.HexColor
---@field public bg_float gt.HexColor
---GitSign Plugin Colors
---@field public git_signs gt.GitSignPalette
