---@class gt.LspPalette
---@field public ref_txt string

---@class gt.PMenuPalette
---@field public bg string
---@field public sbar string

---@class gt.GitPalette
---@field public add string
---@field public change string
---@field public delete string
---@field public conflict string
---@field public ignore string
---@field public renamed string

---@class gt.DiffPalette
---@field public add string
---@field public add_fg string
---@field public change string
---@field public change_fg string
---@field public delete string
---@field public delete_fg string

---@class gt.SyntaxPalette
---@field public comment string
---@field public constant string
---@field public string string
---@field public variable string
---@field public keyword string
---@field public func string
---@field public func_param string
---@field public match_paren_bg string
---@field public tag string
---@field public html_arg string
---@field public param string
---@field public json_label string

---@class gt.GitSignPalette
---@field public add string
---@field public change string
---@field public delete string

---@class gt.ColorPalette
---NONE Color
---@field public none string
---Background Colors
---@field public bg string
---@field public bg2 string
---Foreground Colors
---@field public fg string
---@field public fg_dark string
---@field public fg_gutter string
---@field public fg_light string
---@field public fg_term string
---Background Highlights Colors
---@field public bg_highlight string
---@field public bg_search string
---@field public bg_visual string
---@field public bg_visual_selection string
---@field public border string
---Cursor & LineNumber Colors
---@field public cursor string
---@field public cursor_line_nr string
---@field public line_nr string
---LSP & Diagnostic Colors
---@field public error string
---@field public warning string
---@field public info string
---@field public hint string
---@field public lsp gt.LspPalette
---DropDown Menu Colors
---@field public pmenu gt.PMenuPalette
---Git Colors
---@field public git gt.GitPalette
---Git-Diff Colors
---@field public diff gt.DiffPalette
---Syntax Related Colors
---@field public syntax gt.SyntaxPalette
---Terminal Colors
---@field public orange string
---@field public black string
---@field public bright_black string
---@field public white string
---@field public bright_white string
---@field public red string
---@field public bright_red string
---@field public green string
---@field public bright_green string
---@field public yellow string
---@field public bright_yellow string
---@field public blue string
---@field public bright_blue string
---@field public magenta string
---@field public bright_magenta string
---@field public cyan string
---@field public bright_cyan string
---Configurable Dynamic Colors
---@field public sidebar_eob string
---@field public eob string
---@field public bg_nc_statusline string
---@field public bg_sidebar string
---@field public bg_float string
---GitSign Plugin Colors
---@field public git_signs gt.GitSignPalette
