name: Get/Update Primer Color Primitives

env:
  _DEST_DIR: '${{ github.workspace }}/lua/github-theme/palette/primitives'
  _JSON_DIR: '${{ github.workspace }}/node_modules/@primer/primitives/dist/json/colors'
  _LICENSE_GLOB: '${{ github.workspace }}/node_modules/@primer/primitives/[Ll][Ii][Cc][Ee][Nn][Ss][Ee]*'
  _PRIMITIVES_PKGJSON: '${{ github.workspace }}/node_modules/@primer/primitives/package.json'

on:
  workflow_dispatch:
  schedule:
    # 3x per week (every other day) at 12:40pm Pacific Time
    - cron: '40 19 * * 1,3,5'

jobs:
  get-colors:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
      issues: write
      packages: read
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true

      - run: npm i @primer/primitives@latest

      - run: |
          set -u +f
          shopt -s nocaseglob failglob
          license="$(<$_LICENSE_GLOB)"
          rm -r "$_DEST_DIR" || :
          mkdir -p "$_DEST_DIR"
          cd "$_JSON_DIR"

          if jq -e .version "$_PRIMITIVES_PKGJSON"; then
            version="M._VERSION = vim.json.decode([=[$(jq -e .version "$_PRIMITIVES_PKGJSON")]=], { luanil = { object = false, array = false } })"
          fi

          for file in *.json; do
            cat >|"${_DEST_DIR}/${file%.json}.lua" <<EOF
          -- NOTE: THIS IS AN AUTO-GENERATED FILE. DO NOT EDIT BY-HAND.
          local M = vim.json.decode([=[$(<"$file")]=], { luanil = { object = false, array = false } })
          ${version-}
          M._LICENSE = [=[
          $license]=]
          return M
          EOF
          done

      - uses: JohnnyMorganz/stylua-action@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: -f stylua.toml --verify -- ${{ env._DEST_DIR }}

      - uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Update color primitives
          branch: update-color-primitives
          delete-branch: true
          title: Update color primitives
